# Jekyll Theme Settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Site Settings
title: "CDFM@IIT Delhi"
subtitle: "Research Group Website"
name: "Computation Design of Functional Materials"
description: >
  Welcome to the homepage of the "Computational Design of Functional Materials" research group 
  at the Indian Institute of Technology, Delhi (IIT-D), India. We are part of the Department of 
  Material Science and Engineering (DMSE) and the Department of Chemistry (joint) at IIT Delhi.
locale: "en-US"
breadcrumbs: true
search: true
header:
  logo: "/assets/images/cdfm-logo.png" # Update with your image path

# Site Author
author:
  name: "Dr. Dibyajyoti Ghosh"
  bio: "Assistant Professor, Dept. of Material Science & Engineering and Dept. of Chemistry (joint), IIT Delhi. PI of the Computational Design of Functional Materials (CDFM) group."
  location: "IIT Delhi, India"
  links:
    - label: "Lab Website"
      icon: "fas fa-fw fa-globe"
      url: "https://sites.google.com/view/dibyajyoti-ghosh/home"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/CDFM-IITD"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:dibyajyoti@iitd.ac.in"

# Social Sharing
og_image: "/assets/images/cdfm-logo.png"

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Europe/Paris
atom_feed:
  hide: true

include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      classes: wide
      header:
        teaser: "/assets/images/Mont-Blanc.webp"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      classes: wide
      header:
        overlay_image: "/assets/images/materials.webp"
        overlay_filter: 0.3
        actions:
          - label: "Main Lab Site"
            url: "https://sites.google.com/view/dibyajyoti-ghosh/home"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
